import { Metadata } from 'next';
import './globals.css';
import { Nunito_Sans } from 'next/font/google';
import { Providers } from '@/app/providers';

const nunito = Nunito_Sans({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
