name: Deploy Vercel

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9.6.0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - run: pnpm install

            - name: Deploy to Vercel
              run: npx vercel --prod

              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_SECRET }}
